### PR TITLE
Revert to httpURL for backward compatibility

### PR DESCRIPTION
**Pull request by fabricepipart1a**

### CODE REVIEW

**Comment by t-8ch** [comment]
It would also be possible to have a bw-compat shim that allows falling back reading `httpUrl`. Not sure if needed though

**Comment by fabricepipart1a** [comment]
Good point @t-8ch !
I did not consider that option initially.
At the end it is a matter of deciding what is worse between:
- a field with a name that is not very sexy
- a twitch in the code to manage both fields httpUrl and url

In my opinion the latter is the hardest to understand if you read the code. As a consequence I prefer the slightly oddly named field httpURL.

**Comment by t-8ch** [comment]
One issue I see is that the "field" with a name that is not very sexy is also exposed to end users via CasC and the groovy init scripts.

**Review by clairegallesio1a — APPROVED** [review]
I also agree that this name is really not sexy and that it is exposed to users, so it is not satisfying. In fact, keeping both names to avoid any issue is good for a transition but as Fabrice said, I agree that this is not friendly.

**Pull request merged**
